// Code generated by protoc-gen-go. DO NOT EDIT.
// source: brymck/dates/v1/date.proto

package datesv1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// A Date is a whole or partial calendar date, where the time of day and time zone are not significant.
type Date struct {
	// Year of date
	Year int32 `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	// Month of year
	Month int32 `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	// Day of month
	Day                  int32    `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Date) Reset()         { *m = Date{} }
func (m *Date) String() string { return proto.CompactTextString(m) }
func (*Date) ProtoMessage()    {}
func (*Date) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7dfa3cb07de6ed2, []int{0}
}

func (m *Date) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Date.Unmarshal(m, b)
}
func (m *Date) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Date.Marshal(b, m, deterministic)
}
func (m *Date) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Date.Merge(m, src)
}
func (m *Date) XXX_Size() int {
	return xxx_messageInfo_Date.Size(m)
}
func (m *Date) XXX_DiscardUnknown() {
	xxx_messageInfo_Date.DiscardUnknown(m)
}

var xxx_messageInfo_Date proto.InternalMessageInfo

func (m *Date) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *Date) GetMonth() int32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *Date) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

func init() {
	proto.RegisterType((*Date)(nil), "brymck.dates.v1.Date")
}

func init() { proto.RegisterFile("brymck/dates/v1/date.proto", fileDescriptor_b7dfa3cb07de6ed2) }

var fileDescriptor_b7dfa3cb07de6ed2 = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4a, 0x2a, 0xaa, 0xcc,
	0x4d, 0xce, 0xd6, 0x4f, 0x49, 0x2c, 0x49, 0x2d, 0xd6, 0x2f, 0x33, 0x04, 0x33, 0xf4, 0x0a, 0x8a,
	0xf2, 0x4b, 0xf2, 0x85, 0xf8, 0x21, 0x72, 0x7a, 0x60, 0x39, 0xbd, 0x32, 0x43, 0x25, 0x27, 0x2e,
	0x16, 0x97, 0xc4, 0x92, 0x54, 0x21, 0x21, 0x2e, 0x96, 0xca, 0xd4, 0xc4, 0x22, 0x09, 0x46, 0x05,
	0x46, 0x0d, 0xd6, 0x20, 0x30, 0x5b, 0x48, 0x84, 0x8b, 0x35, 0x37, 0x3f, 0xaf, 0x24, 0x43, 0x82,
	0x09, 0x2c, 0x08, 0xe1, 0x08, 0x09, 0x70, 0x31, 0xa7, 0x24, 0x56, 0x4a, 0x30, 0x83, 0xc5, 0x40,
	0x4c, 0xa7, 0x18, 0x2e, 0xa9, 0xe4, 0xfc, 0x5c, 0xbd, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0x3d,
	0x34, 0x1b, 0x9c, 0x38, 0x41, 0xe6, 0x07, 0x80, 0x6c, 0x0f, 0x60, 0x8c, 0x62, 0x07, 0x0b, 0x97,
	0x19, 0x2e, 0x62, 0x62, 0x76, 0x72, 0x89, 0x58, 0xc5, 0xc4, 0xef, 0x04, 0x51, 0xed, 0x02, 0x56,
	0x1d, 0x66, 0x78, 0x0a, 0x26, 0x12, 0x03, 0x16, 0x89, 0x09, 0x33, 0x4c, 0x62, 0x03, 0xbb, 0xdc,
	0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x01, 0xd2, 0x2b, 0xb8, 0xd7, 0x00, 0x00, 0x00,
}
