// Code generated by protoc-gen-go. DO NOT EDIT.
// source: brymck/risk/v1/risk_api.proto

package riskv1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetRiskRequest struct {
	SecurityId           uint64    `protobuf:"varint,1,opt,name=security_id,json=securityId,proto3" json:"security_id,omitempty"`
	Frequency            Frequency `protobuf:"varint,2,opt,name=frequency,proto3,enum=brymck.risk.v1.Frequency" json:"frequency,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetRiskRequest) Reset()         { *m = GetRiskRequest{} }
func (m *GetRiskRequest) String() string { return proto.CompactTextString(m) }
func (*GetRiskRequest) ProtoMessage()    {}
func (*GetRiskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_96463f50873f2a2d, []int{0}
}

func (m *GetRiskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRiskRequest.Unmarshal(m, b)
}
func (m *GetRiskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRiskRequest.Marshal(b, m, deterministic)
}
func (m *GetRiskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRiskRequest.Merge(m, src)
}
func (m *GetRiskRequest) XXX_Size() int {
	return xxx_messageInfo_GetRiskRequest.Size(m)
}
func (m *GetRiskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRiskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRiskRequest proto.InternalMessageInfo

func (m *GetRiskRequest) GetSecurityId() uint64 {
	if m != nil {
		return m.SecurityId
	}
	return 0
}

func (m *GetRiskRequest) GetFrequency() Frequency {
	if m != nil {
		return m.Frequency
	}
	return Frequency_FREQUENCY_INVALID
}

type GetRiskResponse struct {
	Risk                 float64  `protobuf:"fixed64,1,opt,name=risk,proto3" json:"risk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRiskResponse) Reset()         { *m = GetRiskResponse{} }
func (m *GetRiskResponse) String() string { return proto.CompactTextString(m) }
func (*GetRiskResponse) ProtoMessage()    {}
func (*GetRiskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_96463f50873f2a2d, []int{1}
}

func (m *GetRiskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRiskResponse.Unmarshal(m, b)
}
func (m *GetRiskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRiskResponse.Marshal(b, m, deterministic)
}
func (m *GetRiskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRiskResponse.Merge(m, src)
}
func (m *GetRiskResponse) XXX_Size() int {
	return xxx_messageInfo_GetRiskResponse.Size(m)
}
func (m *GetRiskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRiskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRiskResponse proto.InternalMessageInfo

func (m *GetRiskResponse) GetRisk() float64 {
	if m != nil {
		return m.Risk
	}
	return 0
}

type GetCovariancesRequest struct {
	SecurityIds          []uint64  `protobuf:"varint,1,rep,packed,name=security_ids,json=securityIds,proto3" json:"security_ids,omitempty"`
	Frequency            Frequency `protobuf:"varint,2,opt,name=frequency,proto3,enum=brymck.risk.v1.Frequency" json:"frequency,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetCovariancesRequest) Reset()         { *m = GetCovariancesRequest{} }
func (m *GetCovariancesRequest) String() string { return proto.CompactTextString(m) }
func (*GetCovariancesRequest) ProtoMessage()    {}
func (*GetCovariancesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_96463f50873f2a2d, []int{2}
}

func (m *GetCovariancesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCovariancesRequest.Unmarshal(m, b)
}
func (m *GetCovariancesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCovariancesRequest.Marshal(b, m, deterministic)
}
func (m *GetCovariancesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCovariancesRequest.Merge(m, src)
}
func (m *GetCovariancesRequest) XXX_Size() int {
	return xxx_messageInfo_GetCovariancesRequest.Size(m)
}
func (m *GetCovariancesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCovariancesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCovariancesRequest proto.InternalMessageInfo

func (m *GetCovariancesRequest) GetSecurityIds() []uint64 {
	if m != nil {
		return m.SecurityIds
	}
	return nil
}

func (m *GetCovariancesRequest) GetFrequency() Frequency {
	if m != nil {
		return m.Frequency
	}
	return Frequency_FREQUENCY_INVALID
}

type GetCovariancesResponse struct {
	Covariances          []*CovariancePair `protobuf:"bytes,1,rep,name=covariances,proto3" json:"covariances,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetCovariancesResponse) Reset()         { *m = GetCovariancesResponse{} }
func (m *GetCovariancesResponse) String() string { return proto.CompactTextString(m) }
func (*GetCovariancesResponse) ProtoMessage()    {}
func (*GetCovariancesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_96463f50873f2a2d, []int{3}
}

func (m *GetCovariancesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCovariancesResponse.Unmarshal(m, b)
}
func (m *GetCovariancesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCovariancesResponse.Marshal(b, m, deterministic)
}
func (m *GetCovariancesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCovariancesResponse.Merge(m, src)
}
func (m *GetCovariancesResponse) XXX_Size() int {
	return xxx_messageInfo_GetCovariancesResponse.Size(m)
}
func (m *GetCovariancesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCovariancesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCovariancesResponse proto.InternalMessageInfo

func (m *GetCovariancesResponse) GetCovariances() []*CovariancePair {
	if m != nil {
		return m.Covariances
	}
	return nil
}

type GetReturnTimeSeriesRequest struct {
	SecurityId           uint64    `protobuf:"varint,1,opt,name=security_id,json=securityId,proto3" json:"security_id,omitempty"`
	Frequency            Frequency `protobuf:"varint,2,opt,name=frequency,proto3,enum=brymck.risk.v1.Frequency" json:"frequency,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetReturnTimeSeriesRequest) Reset()         { *m = GetReturnTimeSeriesRequest{} }
func (m *GetReturnTimeSeriesRequest) String() string { return proto.CompactTextString(m) }
func (*GetReturnTimeSeriesRequest) ProtoMessage()    {}
func (*GetReturnTimeSeriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_96463f50873f2a2d, []int{4}
}

func (m *GetReturnTimeSeriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReturnTimeSeriesRequest.Unmarshal(m, b)
}
func (m *GetReturnTimeSeriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReturnTimeSeriesRequest.Marshal(b, m, deterministic)
}
func (m *GetReturnTimeSeriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReturnTimeSeriesRequest.Merge(m, src)
}
func (m *GetReturnTimeSeriesRequest) XXX_Size() int {
	return xxx_messageInfo_GetReturnTimeSeriesRequest.Size(m)
}
func (m *GetReturnTimeSeriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReturnTimeSeriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetReturnTimeSeriesRequest proto.InternalMessageInfo

func (m *GetReturnTimeSeriesRequest) GetSecurityId() uint64 {
	if m != nil {
		return m.SecurityId
	}
	return 0
}

func (m *GetReturnTimeSeriesRequest) GetFrequency() Frequency {
	if m != nil {
		return m.Frequency
	}
	return Frequency_FREQUENCY_INVALID
}

type GetReturnTimeSeriesResponse struct {
	Entries              []*ReturnTimeSeriesEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GetReturnTimeSeriesResponse) Reset()         { *m = GetReturnTimeSeriesResponse{} }
func (m *GetReturnTimeSeriesResponse) String() string { return proto.CompactTextString(m) }
func (*GetReturnTimeSeriesResponse) ProtoMessage()    {}
func (*GetReturnTimeSeriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_96463f50873f2a2d, []int{5}
}

func (m *GetReturnTimeSeriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReturnTimeSeriesResponse.Unmarshal(m, b)
}
func (m *GetReturnTimeSeriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReturnTimeSeriesResponse.Marshal(b, m, deterministic)
}
func (m *GetReturnTimeSeriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReturnTimeSeriesResponse.Merge(m, src)
}
func (m *GetReturnTimeSeriesResponse) XXX_Size() int {
	return xxx_messageInfo_GetReturnTimeSeriesResponse.Size(m)
}
func (m *GetReturnTimeSeriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReturnTimeSeriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetReturnTimeSeriesResponse proto.InternalMessageInfo

func (m *GetReturnTimeSeriesResponse) GetEntries() []*ReturnTimeSeriesEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func init() {
	proto.RegisterType((*GetRiskRequest)(nil), "brymck.risk.v1.GetRiskRequest")
	proto.RegisterType((*GetRiskResponse)(nil), "brymck.risk.v1.GetRiskResponse")
	proto.RegisterType((*GetCovariancesRequest)(nil), "brymck.risk.v1.GetCovariancesRequest")
	proto.RegisterType((*GetCovariancesResponse)(nil), "brymck.risk.v1.GetCovariancesResponse")
	proto.RegisterType((*GetReturnTimeSeriesRequest)(nil), "brymck.risk.v1.GetReturnTimeSeriesRequest")
	proto.RegisterType((*GetReturnTimeSeriesResponse)(nil), "brymck.risk.v1.GetReturnTimeSeriesResponse")
}

func init() { proto.RegisterFile("brymck/risk/v1/risk_api.proto", fileDescriptor_96463f50873f2a2d) }

var fileDescriptor_96463f50873f2a2d = []byte{
	// 444 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0x5d, 0x8b, 0xd3, 0x40,
	0x14, 0x25, 0xd9, 0xb2, 0xc5, 0x9b, 0x25, 0xc2, 0x88, 0xd2, 0x8d, 0xb8, 0xad, 0x81, 0x4a, 0x51,
	0xcc, 0x92, 0xfa, 0xe0, 0xa3, 0x1a, 0xd1, 0x65, 0x7d, 0x0a, 0xa3, 0x2c, 0xb2, 0x2e, 0x86, 0x34,
	0x3b, 0xea, 0x58, 0xf2, 0xe1, 0xcc, 0x24, 0xd0, 0xbf, 0xe3, 0x83, 0x0f, 0xfe, 0x14, 0x7f, 0x95,
	0xcc, 0xe4, 0xab, 0x3b, 0x8d, 0x28, 0xc2, 0x3e, 0xb5, 0xdc, 0x7b, 0xce, 0x9c, 0x73, 0xef, 0xb9,
	0x81, 0x7b, 0x2b, 0xb6, 0x49, 0x93, 0xf5, 0x31, 0xa3, 0x7c, 0x7d, 0x5c, 0xf9, 0xea, 0x37, 0x8a,
	0x0b, 0xea, 0x15, 0x2c, 0x17, 0x39, 0xb2, 0xeb, 0xb6, 0x27, 0xcb, 0x5e, 0xe5, 0x3b, 0x53, 0x0d,
	0x9e, 0xe4, 0x55, 0xcc, 0x68, 0x9c, 0x25, 0xa4, 0x26, 0x38, 0x47, 0x1a, 0xe0, 0x13, 0x23, 0xdf,
	0x4a, 0x92, 0x25, 0x9b, 0xa6, 0xff, 0x58, 0xd7, 0x23, 0xa2, 0x64, 0x59, 0x24, 0x68, 0x4a, 0x22,
	0x4e, 0x18, 0x25, 0x3c, 0x22, 0x99, 0x60, 0x0d, 0xdc, 0xfd, 0x0a, 0xf6, 0x09, 0x11, 0x98, 0xf2,
	0x35, 0x96, 0xef, 0x70, 0x81, 0xa6, 0x60, 0x71, 0x92, 0x94, 0x8c, 0x8a, 0x4d, 0x44, 0x2f, 0x27,
	0xc6, 0xcc, 0x58, 0x8c, 0x30, 0xb4, 0xa5, 0xd3, 0x4b, 0xf4, 0x14, 0x6e, 0x74, 0xa2, 0x13, 0x73,
	0x66, 0x2c, 0xec, 0xe5, 0xa1, 0x77, 0x75, 0x0c, 0xef, 0x75, 0x0b, 0xc0, 0x3d, 0xd6, 0x9d, 0xc3,
	0xcd, 0x4e, 0x8b, 0x17, 0x79, 0xc6, 0x09, 0x42, 0x30, 0x92, 0x14, 0xa5, 0x62, 0x60, 0xf5, 0xdf,
	0xe5, 0x70, 0xfb, 0x84, 0x88, 0x97, 0xdd, 0xe0, 0xbc, 0x75, 0x76, 0x1f, 0x0e, 0xb6, 0x9c, 0xf1,
	0x89, 0x31, 0xdb, 0x5b, 0x8c, 0xb0, 0xd5, 0x5b, 0xe3, 0xff, 0xef, 0xed, 0x1c, 0xee, 0xe8, 0xa2,
	0x8d, 0xc5, 0xe7, 0x60, 0xf5, 0x21, 0xd4, 0xa2, 0xd6, 0xf2, 0x48, 0x7f, 0xb4, 0x67, 0x86, 0x31,
	0x65, 0x78, 0x9b, 0xe2, 0x56, 0xe0, 0xc8, 0xb9, 0x55, 0x10, 0xef, 0x68, 0x4a, 0xde, 0xaa, 0x18,
	0xae, 0x7f, 0xdf, 0x1f, 0xe1, 0xee, 0xa0, 0x6e, 0x33, 0xd8, 0x33, 0x18, 0xcb, 0x4b, 0xa0, 0xdd,
	0x50, 0x73, 0xfd, 0x55, 0x9d, 0xfa, 0x4a, 0x1e, 0x0e, 0x6e, 0x59, 0xcb, 0x1f, 0x26, 0x8c, 0x65,
	0x9a, 0x2f, 0xc2, 0x53, 0xf4, 0x06, 0xc6, 0x4d, 0xb6, 0x68, 0x67, 0x37, 0x57, 0x0f, 0xcc, 0x99,
	0xfe, 0xb1, 0xdf, 0x18, 0x8b, 0xd4, 0x4d, 0x6e, 0x65, 0x81, 0xe6, 0x03, 0x94, 0xdd, 0x03, 0x71,
	0x1e, 0xfc, 0x0d, 0xd6, 0x08, 0x64, 0x70, 0x6b, 0x60, 0x31, 0xe8, 0xe1, 0x90, 0xb1, 0xe1, 0xd4,
	0x9c, 0x47, 0xff, 0x84, 0xad, 0xf5, 0x82, 0x0f, 0x70, 0x98, 0xe4, 0xa9, 0xf7, 0x99, 0x8a, 0x2f,
	0xe5, 0x4a, 0x23, 0x06, 0x07, 0x6a, 0x85, 0x05, 0x0d, 0xe5, 0xf7, 0x18, 0x1a, 0xe7, 0xfb, 0xb2,
	0x51, 0xf9, 0xdf, 0xcd, 0xbd, 0x00, 0xbf, 0xff, 0x69, 0xda, 0x41, 0x0d, 0x97, 0x28, 0xef, 0xcc,
	0xff, 0xd5, 0x16, 0x2e, 0x64, 0xe1, 0xe2, 0xcc, 0x5f, 0xed, 0xab, 0x0f, 0xf9, 0xc9, 0xef, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x5a, 0xe5, 0xef, 0x22, 0x69, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RiskAPIClient is the client API for RiskAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RiskAPIClient interface {
	// GetRisk gets ex ante risk for a security.
	GetRisk(ctx context.Context, in *GetRiskRequest, opts ...grpc.CallOption) (*GetRiskResponse, error)
	// GetCovariances retrieves covariances for a list of securities.
	GetCovariances(ctx context.Context, in *GetCovariancesRequest, opts ...grpc.CallOption) (*GetCovariancesResponse, error)
	// GetReturnTimeSeries retrieves the return time series for a security.
	GetReturnTimeSeries(ctx context.Context, in *GetReturnTimeSeriesRequest, opts ...grpc.CallOption) (*GetReturnTimeSeriesResponse, error)
}

type riskAPIClient struct {
	cc *grpc.ClientConn
}

func NewRiskAPIClient(cc *grpc.ClientConn) RiskAPIClient {
	return &riskAPIClient{cc}
}

func (c *riskAPIClient) GetRisk(ctx context.Context, in *GetRiskRequest, opts ...grpc.CallOption) (*GetRiskResponse, error) {
	out := new(GetRiskResponse)
	err := c.cc.Invoke(ctx, "/brymck.risk.v1.RiskAPI/GetRisk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskAPIClient) GetCovariances(ctx context.Context, in *GetCovariancesRequest, opts ...grpc.CallOption) (*GetCovariancesResponse, error) {
	out := new(GetCovariancesResponse)
	err := c.cc.Invoke(ctx, "/brymck.risk.v1.RiskAPI/GetCovariances", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskAPIClient) GetReturnTimeSeries(ctx context.Context, in *GetReturnTimeSeriesRequest, opts ...grpc.CallOption) (*GetReturnTimeSeriesResponse, error) {
	out := new(GetReturnTimeSeriesResponse)
	err := c.cc.Invoke(ctx, "/brymck.risk.v1.RiskAPI/GetReturnTimeSeries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RiskAPIServer is the server API for RiskAPI service.
type RiskAPIServer interface {
	// GetRisk gets ex ante risk for a security.
	GetRisk(context.Context, *GetRiskRequest) (*GetRiskResponse, error)
	// GetCovariances retrieves covariances for a list of securities.
	GetCovariances(context.Context, *GetCovariancesRequest) (*GetCovariancesResponse, error)
	// GetReturnTimeSeries retrieves the return time series for a security.
	GetReturnTimeSeries(context.Context, *GetReturnTimeSeriesRequest) (*GetReturnTimeSeriesResponse, error)
}

func RegisterRiskAPIServer(s *grpc.Server, srv RiskAPIServer) {
	s.RegisterService(&_RiskAPI_serviceDesc, srv)
}

func _RiskAPI_GetRisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskAPIServer).GetRisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/brymck.risk.v1.RiskAPI/GetRisk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskAPIServer).GetRisk(ctx, req.(*GetRiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskAPI_GetCovariances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCovariancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskAPIServer).GetCovariances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/brymck.risk.v1.RiskAPI/GetCovariances",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskAPIServer).GetCovariances(ctx, req.(*GetCovariancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskAPI_GetReturnTimeSeries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReturnTimeSeriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskAPIServer).GetReturnTimeSeries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/brymck.risk.v1.RiskAPI/GetReturnTimeSeries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskAPIServer).GetReturnTimeSeries(ctx, req.(*GetReturnTimeSeriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RiskAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "brymck.risk.v1.RiskAPI",
	HandlerType: (*RiskAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRisk",
			Handler:    _RiskAPI_GetRisk_Handler,
		},
		{
			MethodName: "GetCovariances",
			Handler:    _RiskAPI_GetCovariances_Handler,
		},
		{
			MethodName: "GetReturnTimeSeries",
			Handler:    _RiskAPI_GetReturnTimeSeries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "brymck/risk/v1/risk_api.proto",
}
